define(function(require, exports, module) {

	exports.daily = function() {
		return {
			type: "daily",
			name: "日常",
			description: "",
			icons: [{
				name: "四宫格",
				description: "",
				url: "images/icons/daily/4gongge.svg"
			}, {
				name: "九宫格",
				description: "",
				url: "images/icons/daily/9gongge.svg"
			}, {
				name: "bad",
				description: "",
				url: "images/icons/daily/bad.svg"
			}, {
				name: "bear",
				description: "",
				url: "images/icons/daily/bear.svg"
			}, {
				name: "bike",
				description: "",
				url: "images/icons/daily/bike.svg"
			}, {
				name: "book",
				description: "",
				url: "images/icons/daily/book.svg"
			}, {
				name: "bus",
				description: "",
				url: "images/icons/daily/bus.svg"
			}, {
				name: "caipiao",
				description: "",
				url: "images/icons/daily/caipiao.svg"
			}, {
				name: "calendar",
				description: "",
				url: "images/icons/daily/calendar.svg"
			}, {
				name: "camera",
				description: "",
				url: "images/icons/daily/camera.svg"
			}, {
				name: "closexizhuang",
				description: "",
				url: "images/icons/daily/closexizhuang.svg"
			}, {
				name: "damon",
				description: "",
				url: "images/icons/daily/damon.svg"
			}, {
				name: "delete",
				description: "",
				url: "images/icons/daily/delete.svg"
			}, {
				name: "dunpai",
				description: "",
				url: "images/icons/daily/dunpai.svg"
			}, {
				name: "edite",
				description: "",
				url: "images/icons/daily/edite.svg"
			}, {
				name: "feiji",
				description: "",
				url: "images/icons/daily/feiji.svg"
			}, {
				name: "fujian",
				description: "",
				url: "images/icons/daily/fujian.svg"
			}, {
				name: "game",
				description: "",
				url: "images/icons/daily/game.svg"
			}, {
				name: "game2",
				description: "",
				url: "images/icons/daily/game2.svg"
			}, {
				name: "gift",
				description: "",
				url: "images/icons/daily/gift.svg"
			}, {
				name: "gift2",
				description: "",
				url: "images/icons/daily/gift2.svg"
			}, {
				name: "good",
				description: "",
				url: "images/icons/daily/good.svg"
			}, {
				name: "hongbao",
				description: "",
				url: "images/icons/daily/hongbao.svg"
			}, {
				name: "images",
				description: "",
				url: "images/icons/daily/images.svg"
			}, {
				name: "iphone",
				description: "",
				url: "images/icons/daily/iphone.svg"
			}, {
				name: "jiandao",
				description: "",
				url: "images/icons/daily/jiandao.svg"
			}, {
				name: "jita",
				description: "",
				url: "images/icons/daily/jita.svg"
			}, {
				name: "jiweijiu",
				description: "",
				url: "images/icons/daily/jiweijiu.svg"
			}, {
				name: "juanzhi",
				description: "",
				url: "images/icons/daily/juanzhi.svg"
			}, {
				name: "kafei",
				description: "",
				url: "images/icons/daily/kafei.svg"
			}, {
				name: "liebiao",
				description: "",
				url: "images/icons/daily/liebiao.svg"
			}, {
				name: "love",
				description: "",
				url: "images/icons/daily/love.svg"
			}, {
				name: "loves",
				description: "",
				url: "images/icons/daily/loves.svg"
			}, {
				name: "man",
				description: "",
				url: "images/icons/daily/man.svg"
			}, {
				name: "medtion",
				description: "",
				url: "images/icons/daily/medtion.svg"
			}, {
				name: "movie",
				description: "",
				url: "images/icons/daily/movie.svg"
			}, {
				name: "music2",
				description: "",
				url: "images/icons/daily/music2.svg"
			}, {
				name: "nifeforks",
				description: "",
				url: "images/icons/daily/nifeforks.svg"
			}, {
				name: "pad",
				description: "",
				url: "images/icons/daily/pad.svg"
			}, {
				name: "people",
				description: "",
				url: "images/icons/daily/people.svg"
			}, {
				name: "phone",
				description: "",
				url: "images/icons/daily/phone.svg"
			}, {
				name: "position",
				description: "",
				url: "images/icons/daily/position.svg"
			}, {
				name: "qianbao",
				description: "",
				url: "images/icons/daily/qianbao.svg"
			}, {
				name: "qianbao1",
				description: "",
				url: "images/icons/daily/qianbao1.svg"
			}, {
				name: "radio",
				description: "",
				url: "images/icons/daily/radio.svg"
			}, {
				name: "right",
				description: "",
				url: "images/icons/daily/right.svg"
			}, {
				name: "search",
				description: "",
				url: "images/icons/daily/search.svg"
			}, {
				name: "setting",
				description: "",
				url: "images/icons/daily/setting.svg"
			}, {
				name: "shenfenzheng",
				description: "",
				url: "images/icons/daily/shenfenzheng.svg"
			}, {
				name: "shop",
				description: "",
				url: "images/icons/daily/shop.svg"
			}, {
				name: "shoseman",
				description: "",
				url: "images/icons/daily/shoseman.svg"
			}, {
				name: "shosesport",
				description: "",
				url: "images/icons/daily/shosesport.svg"
			}, {
				name: "shosewomen",
				description: "",
				url: "images/icons/daily/shosewomen.svg"
			}, {
				name: "speaker",
				description: "",
				url: "images/icons/daily/speaker.svg"
			}, {
				name: "stars",
				description: "",
				url: "images/icons/daily/stars.svg"
			}, {
				name: "stars2",
				description: "",
				url: "images/icons/daily/stars2.svg"
			}, {
				name: "tags",
				description: "",
				url: "images/icons/daily/tags.svg"
			}, {
				name: "talk",
				description: "",
				url: "images/icons/daily/talk.svg"
			}, {
				name: "taxi",
				description: "",
				url: "images/icons/daily/taxi.svg"
			}, {
				name: "tianjia",
				description: "",
				url: "images/icons/daily/tianjia.svg"
			}, {
				name: "timer",
				description: "",
				url: "images/icons/daily/timer.svg"
			}, {
				name: "train",
				description: "",
				url: "images/icons/daily/train.svg"
			}, {
				name: "tuijian",
				description: "",
				url: "images/icons/daily/tuijian.svg"
			}, {
				name: "umbraller",
				description: "",
				url: "images/icons/daily/umbraller.svg"
			}, {
				name: "weishengjin",
				description: "",
				url: "images/icons/daily/weishengjin.svg"
			}, {
				name: "wenhao",
				description: "",
				url: "images/icons/daily/wenhao.svg"
			}, {
				name: "wenzhang",
				description: "",
				url: "images/icons/daily/wenzhang.svg"
			}, {
				name: "wether",
				description: "",
				url: "images/icons/daily/wether.svg"
			}, {
				name: "windows",
				description: "",
				url: "images/icons/daily/windows.svg"
			}, {
				name: "women2",
				description: "",
				url: "images/icons/daily/women2.svg"
			}, {
				name: "women",
				description: "",
				url: "images/icons/daily/women.svg"
			}, {
				name: "wrong",
				description: "",
				url: "images/icons/daily/wrong.svg"
			}, {
				name: "xin",
				description: "",
				url: "images/icons/daily/xin.svg"
			}, {
				name: "yinyue",
				description: "",
				url: "images/icons/daily/yinyue.svg"
			}, {
				name: "zhifeiji",
				description: "",
				url: "images/icons/daily/zhifeiji.svg"
			}, {
				name: "zhiwu",
				description: "",
				url: "images/icons/daily/zhiwu.svg"
			}]
		};
	};

	exports.line=function(){
		return {
			type: "line",
			name: "线条",
			description: "",
			icons: [{
				name: "caidan",
				description: "",
				url: "images/icons/line/caidan.svg"
			}, {
				name: "camera",
				description: "",
				url: "images/icons/line/camera.svg"
			}, {
				name: "coment",
				description: "",
				url: "images/icons/line/coment.svg"
			}, {
				name: "cothse",
				description: "",
				url: "images/icons/line/cothse.svg"
			}, {
				name: "edite",
				description: "",
				url: "images/icons/line/edite.svg"
			}, {
				name: "erweima",
				description: "",
				url: "images/icons/line/erweima.svg"
			}, {
				name: "femal",
				description: "",
				url: "images/icons/line/femal.svg"
			}, {
				name: "form",
				description: "",
				url: "images/icons/line/form.svg"
			}, {
				name: "game",
				description: "",
				url: "images/icons/line/game.svg"
			}, {
				name: "gifts",
				description: "",
				url: "images/icons/line/gifts.svg"
			}, {
				name: "good",
				description: "",
				url: "images/icons/line/good.svg"
			}, {
				name: "home",
				description: "",
				url: "images/icons/line/home.svg"
			}, {
				name: "images",
				description: "",
				url: "images/icons/line/images.svg"
			}, {
				name: "location",
				description: "",
				url: "images/icons/line/location.svg"
			}, {
				name: "male",
				description: "",
				url: "images/icons/line/male.svg"
			}, {
				name: "me",
				description: "",
				url: "images/icons/line/me.svg"
			}, {
				name: "mingxing",
				description: "",
				url: "images/icons/line/mingxing.svg"
			}, {
				name: "mobile",
				description: "",
				url: "images/icons/line/mobile.svg"
			}, {
				name: "money",
				description: "",
				url: "images/icons/line/money.svg"
			}, {
				name: "naozhong",
				description: "",
				url: "images/icons/line/naozhong.svg"
			}, {
				name: "notice",
				description: "",
				url: "images/icons/line/notice.svg"
			}, {
				name: "peoples",
				description: "",
				url: "images/icons/line/peoples.svg"
			}, {
				name: "phonebook",
				description: "",
				url: "images/icons/line/phonebook.svg"
			}, {
				name: "plant",
				description: "",
				url: "images/icons/line/plant.svg"
			}, {
				name: "rank",
				description: "",
				url: "images/icons/line/rank.svg"
			}, {
				name: "right",
				description: "",
				url: "images/icons/line/right.svg"
			}, {
				name: "scan",
				description: "",
				url: "images/icons/line/scan.svg"
			}, {
				name: "search",
				description: "",
				url: "images/icons/line/search.svg"
			}, {
				name: "setting",
				description: "",
				url: "images/icons/line/setting.svg"
			}, {
				name: "shop",
				description: "",
				url: "images/icons/line/shop.svg"
			}, {
				name: "smaile",
				description: "",
				url: "images/icons/line/smaile.svg"
			}, {
				name: "speaker",
				description: "",
				url: "images/icons/line/speaker.svg"
			}, {
				name: "stars",
				description: "",
				url: "images/icons/line/stars.svg"
			}, {
				name: "tags",
				description: "",
				url: "images/icons/line/tags.svg"
			}, {
				name: "taxi",
				description: "",
				url: "images/icons/line/taxi.svg"
			}, {
				name: "time",
				description: "",
				url: "images/icons/line/time.svg"
			}, {
				name: "timer",
				description: "",
				url: "images/icons/line/timer.svg"
			}, {
				name: "voise",
				description: "",
				url: "images/icons/line/voise.svg"
			}, {
				name: "wenhao",
				description: "",
				url: "images/icons/line/wenhao.svg"
			}, {
				name: "worning",
				description: "",
				url: "images/icons/line/worning.svg"
			}, {
				name: "wrong",
				description: "",
				url: "images/icons/line/wrong.svg"
			}]
		};
	};

	exports.constellation=function(){
		return {
			type: "constellation",
			name: "星座",
			description: "",
			icons: [{
				name: "chunv",
				description: "",
				url: "images/icons/constellation/chunv.svg"
			}, {
				name: "jinniu",
				description: "",
				url: "images/icons/constellation/jinniu.svg"
			}, {
				name: "juxie",
				description: "",
				url: "images/icons/constellation/juxie.svg"
			}, {
				name: "jinniu",
				description: "",
				url: "images/icons/constellation/jinniu.svg"
			}, {
				name: "moxie",
				description: "",
				url: "images/icons/constellation/moxie.svg"
			}, {
				name: "muyang",
				description: "",
				url: "images/icons/constellation/muyang.svg"
			}, {
				name: "sheshou",
				description: "",
				url: "images/icons/constellation/sheshou.svg"
			}, {
				name: "shizi",
				description: "",
				url: "images/icons/constellation/shizi.svg"
			}, {
				name: "shuangyu",
				description: "",
				url: "images/icons/constellation/shuangyu.svg"
			}, {
				name: "shuangzi",
				description: "",
				url: "images/icons/constellation/shuangzi.svg"
			}, {
				name: "shuiping",
				description: "",
				url: "images/icons/constellation/shuiping.svg"
			}, {
				name: "tiancheng",
				description: "",
				url: "images/icons/constellation/tiancheng.svg"
			}, {
				name: "tianxie",
				description: "",
				url: "images/icons/constellation/tianxie.svg"
			}]
		};
	};

	exports.food=function(){
		return {
			type: "food",
			name: "食物",
			description: "",
			icons: [{
				name: "hanbao",
				description: "",
				url: "images/icons/food/hanbao.svg"
			}, {
				name: "naicha",
				description: "",
				url: "images/icons/food/naicha.svg"
			}, {
				name: "regou",
				description: "",
				url: "images/icons/food/regou.svg"
			}, {
				name: "sousi",
				description: "",
				url: "images/icons/food/sousi.svg"
			}, {
				name: "tanghulu",
				description: "",
				url: "images/icons/food/tanghulu.svg"
			}, {
				name: "tiantianquan",
				description: "",
				url: "images/icons/food/tiantianquan.svg"
			}]
		};
	};

	exports.text=function(){
		return {
			type: "text",
			name: "文本",
			description: "",
			icons: [{
				name: "pin",
				description: "",
				url: "images/icons/text/pin.svg"
			}, {
				name: "qian",
				description: "",
				url: "images/icons/text/qian.svg"
			}, {
				name: "re",
				description: "",
				url: "images/icons/text/re.svg"
			}, {
				name: "xin",
				description: "",
				url: "images/icons/text/xin.svg"
			}, {
				name: "you",
				description: "",
				url: "images/icons/text/you.svg"
			}]
		};
	};

});